apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bedrock-stage-data
  namespace: bedrock-stage
  labels:
    k8s-app: bedrock-stage-data
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 5
    type: RollingUpdate
  selector:
    matchLabels:
      name: bedrock-stage-data
  template:
    metadata:
      labels:
        name: bedrock-stage-data
    spec:
      containers:
      - name: bedrock-stage-data
        image: mozmeao/bedrock:c0b817ac215126c508c4c13451222dd5a8cf61da
        imagePullPolicy: IfNotPresent
        args:
          - ./bin/run-file-clock.sh
        command:
          - /bin/bash
          - -c
        env:
          - name: AWS_DB_S3_BUCKET
            value: bedrock-db-stage
          - name: CLUSTER_NAME
            valueFrom:
              configMapKeyRef:
                name: bedrock-stage-configmap
                key: CLUSTER_NAME
          - name: DB_DOWNLOAD_IGNORE_GIT
            value: "False"
          - name: DEBUG
            value: "False"
          - name: DEV
            value: "False"
          - name: LOGLEVEL
            value: info
          - name: NEW_RELIC_APP_NAME
            valueFrom:
              configMapKeyRef:
                name: bedrock-stage-configmap
                key: NEW_RELIC_APP_NAME
          - name: NEW_RELIC_LICENSE_KEY
            valueFrom:
              secretKeyRef:
                key: new-relic-license-key
                name: bedrock-stage-secrets
          - name: PROD
            value: "True"
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                key: secret-key
                name: bedrock-stage-secrets
          - name: SENTRY_DSN
            value: "https://b01c999bc1b0489bad23805c55660a22@sentry.prod.mozaws.net/151"
          - name: STATSD_CLIENT
            value: django_statsd.clients.normal
        resources:
          limits:
            cpu: 350m
            memory: 250Mi
          requests:
            cpu: 200m
            memory: 150Mi
        volumeMounts:
        - name: data
          mountPath: /app/data
      priorityClassName: high-priority-preempting
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      volumes:
      - name: data
        hostPath:
          path: /var/lib/bedrock-stage/data
