apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: bedrock-test
    type: web
  name: bedrock-test-web
  namespace: bedrock-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: bedrock-test
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 5
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bedrock-test
        type: web
      name: bedrock-test-web
      namespace: bedrock-test
    spec:
      containers:
      - args:
        - ./bin/run.sh
        command:
        - /bin/bash
        - -c
        env:
        - name: ALLOWED_HOSTS
          value: "*"
        - name: BASKET_API_KEY
          valueFrom:
            secretKeyRef:
              key: basket-api-key
              name: bedrock-test-secrets
        - name: BASKET_URL
          value: https://basket.allizom.org
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: bedrock-test-configmap
              key: CLUSTER_NAME
        - name: CSP_DEFAULT_SRC
          value: "*.allizom.org"
        - name: CSP_REPORT_ENABLE
          value: "True"
        - name: DEBUG
          value: "False"
        - name: DEIS_DOMAIN
          valueFrom:
            configMapKeyRef:
              name: bedrock-test-configmap
              key: DEIS_DOMAIN
        - name: DEV
          value: "True"
        - name: DISABLE_SSL
          value: "False"
        - name: ENABLE_CSP_MIDDLEWARE
          value: "True"
        - name: ENABLE_HOSTNAME_MIDDLEWARE
          value: "True"
        - name: GTM_CONTAINER_ID
          value: GTM-MW3R8V
        - name: HTTPS
          value: "on"
        - name: L10N_CRON
          value: "True"
        - name: LOGLEVEL
          value: info
        - name: MOFO_SECURITY_ADVISORIES_BRANCH
          value: testing
        - name: MOFO_SECURITY_ADVISORIES_PATH
          value: /tmp/mofo_security_advisories
        - name: NEW_RELIC_APP_NAME
          valueFrom:
            configMapKeyRef:
              name: bedrock-test-configmap
              key: NEW_RELIC_APP_NAME
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: new-relic-license-key
              name: bedrock-test-secrets
        - name: PROD
          value: "True"
        - name: RUN_SUPERVISOR
          value: "True"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: bedrock-test-secrets
        - name: SECURE_BROWSER_XSS_FILTER
          value: "True"
        - name: SECURE_HSTS_SECONDS
          value: "31536000"
        - name: SECURE_SSL_REDIRECT
          value: "True"
        - name: SENTRY_DSN
          value: "https://b89cacf912c24702a2fa6e3dc4610ade@sentry.prod.mozaws.net/156"
        - name: STATIC_URL
          value: "https://bedrock-test.moz.works/media/"
        - name: STATSD_CLIENT
          value: django_statsd.clients.normal
        - name: SWITCH_NEWSLETTER_MAINTENANCE_MODE
          value: "False"
        image: mozmeao/bedrock:21387786ed24fac7bd5d6fc7641e38c9a728a8b7
        imagePullPolicy: IfNotPresent
        name: bedrock-test-web
        ports:
          - containerPort: 8000
        livenessProbe:
          failureThreshold: 4
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /healthz/
            scheme: HTTP
            port: 8000
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 20
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
          httpGet:
            path: /readiness/
            scheme: HTTP
            port: 8000
        resources:
          limits:
            cpu: 1500m
            memory: 1000Mi
          requests:
            cpu: 750m
            memory: 600Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
