apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: bedrock-geoip
  namespace: bedrock-prod
  labels:
    k8s-app: bedrock-geoip
spec:
  selector:
    matchLabels:
      name: bedrock-geoip
  template:
    metadata:
      labels:
        name: bedrock-geoip
    spec:
      containers:
        - name: bedrock-geoip
          image: maxmindinc/geoipupdate:v4.3
          imagePullPolicy: IfNotPresent
          env:
            - name: GEOIPUPDATE_EDITION_IDS
              value: GeoIP2-Country
            - name: GEOIPUPDATE_FREQUENCY
              value: 24
            - name: GEOIPUPDATE_ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  key: geoipupdate-account-id
                  name: bedrock-prod-secrets
            - name: GEOIPUPDATE_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  key: geoipupdate-license-key
                  name: bedrock-prod-secrets
          resources:
            limits:
              cpu: 1500m
              memory: 1000Mi
            requests:
              cpu: 750m
              memory: 600Mi
          volumeMounts:
            - name: data
              mountPath: /usr/share/GeoIP
      terminationGracePeriodSeconds: 30
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0
      volumes:
        - name: data
          hostPath:
            path: /var/lib/bedrock-all/geoip
