apiVersion: v1
kind: ConfigMap
metadata:
    name: bedrock-dev-configmap
    namespace: bedrock-dev
data:
    NEW_RELIC_APP_NAME: bedrock-dev-iowa-a;bedrock-dev
    # TODO: DEPRECATE DEIS_DOMAIN IN FAVOR OF CLUSTER_NAME
    DEIS_DOMAIN: gcp.moz.works
    CLUSTER_NAME: iowa-a
